### ISSUE TITLE
Should the Attending and Availability Notes Show up on past activities

### ISSUE THREAD

**Issue by latazzajones** [CZagrobelny/new_sanctuary_asylum#187]
I'm cleaning up `app/views/accompaniment_leader/activities/_accompaniment_modal.html.erb` a little bit before working on issue https://github.com/CZagrobelny/new_sanctuary_asylum/issues/176 and have a couple of questions: 

1. Do we want the "Attending and Availability Notes" fields to show up if an activity is past? 
2. Do  we want to show the "Add a Report Back/Edit my Report Back" link if the activity han't happend yet? 

Here's a screenshot of the modal:  

<img width="604" alt="screen shot 2019-02-06 at 10 27 05 am" src="https://user-images.githubusercontent.com/6585221/52352250-45231280-29fa-11e9-9bbc-b448ba95610b.png">

I assume we'd want to make corrisponding changes to the Admin modal too.

**Comment by CZagrobelny** [comment]
@latazzajones 
1. The attendance data is helpful for admins, availability notes aren't used too frequently, but I think it's worth keeping them there for consistency
2.  Yes, occasionally the volunteer who is calling all of the friends before their accompaniments, will use the report back to add a note.  It doesn't happen that often, but it could throw them off if we changed it.

That being said, I can see this accompaniment modal could get a bit unwieldy.  I have a product manager volunteer who has been wanting to do user interviews to help us refine parts of the functionality.  I think we should do that here.  There are 42 accompaniment leaders and I usually try to change as little as possible because I haven't really established a direct line of communication to them and they've gotten thrown off by unexpected changes in the past.

**Comment by latazzajones** [comment]
@CZagrobelny 👍 sounds good. I'm gunna close this and leave the modal more or less as is then just add a link so the leader can add an activity.
